#ifndef HAMN_IMAGE_VARIATIONS_H
#define HAMN_IMAGE_VARIATIONS_H

/*
 * Generate real cleanup variations from one exported provisioned baseline.
 *
 * Requires Linux arm64, libguestfs and the normal builder dependencies. This
 * is an explicitly invoked integration fixture, not a portable synthetic
 * test. It never changes the supplied image or boots a VM. Its output index
 * deliberately marks physical runtime validation pending for every exact
 * image digest.
 *
 * Plans and generated bytes reproduce CPython's random.Random for the same
 * seeds, so seeds recorded by earlier variations.json files keep meaning the
 * same inputs.
 */

#include <stddef.h>
#include <stdint.h>

#include "image/image_util.h"

#define VARIATION_MAX_CASES 4
#define VARIATION_DEFAULT_SEED 20260921
#define VARIATION_DEFAULT_CASES 2

struct variation_case {
    unsigned index;
    uint32_t seed;
    unsigned regenerable_bytes;   /* per generated file; 0 for case 0 */
};

/*
 * CPython random.Random(SEED): each case draws randrange(2**32) as its seed
 * and, except case 0, randrange(1024, 65537) bytes per file. SEED must fit
 * uint32 and COUNT must be 1..4.
 */
int variations_plan(long long seed, long long count,
                    struct variation_case cases[VARIATION_MAX_CASES],
                    struct image_error *error);

/*
 * Writes one case's guest payload into the existing DIRECTORY as files
 * "log", "deb", "tmp", "var-tmp" (random.Random(case seed).randbytes each),
 * "machine-id" (16 random bytes as hex plus a newline) and "ssh-host-key"
 * (64 random bytes). Existing files are never replaced.
 */
int variations_write_payload(const struct variation_case *variation,
                             const char *directory, struct image_error *error);

/* The fixed guest command that installs a copied-in payload directory. */
extern const char variations_guest_install_command[];

/*
 * Fails unless the dpkg inventory at PATH (read like size_package_inventory)
 * equals EXPECTED, the pinned packagesAfter array of the baseline's report.
 */
int variations_verify_inventory(const char *path,
                                const struct json_value *expected,
                                struct image_error *error);

struct variations_options {
    const char *source_root;      /* Hamn checkout with guest/ and host/ */
    const char *baseline;         /* exported pre-cleanup baseline */
    const char *size_report;      /* the same build's size report */
    const char *output_directory; /* must not exist; parent owned, 0755-safe */
    long long seed;
    long long case_count;
};

/*
 * Runs the whole Linux-only generation; see docs/RELEASE-SETUP.md. External
 * commands run in their own session with stdin from /dev/null; each has a
 * deadline (20 minutes, 5 for the package query, 5 s for git) after which,
 * or on SIGINT/SIGTERM/SIGHUP, its whole process group is terminated and
 * reaped. The private stage is removed on every exit; logs and completed
 * cases stay in the output directory. Builds with -DHAMN_TEST (tests only)
 * honor HAMN_TEST_VARIATIONS_HOST (skip the host check) and
 * HAMN_TEST_VARIATIONS_TIMEOUT (seconds for every deadline).
 */
int variations_run(const struct variations_options *options,
                   struct image_error *error);

#endif
